use day2;

select * from fact;
select * from location;
select * from product;

-- 1. display the number of states present in the location table

select count(distinct state) as total_states
from location;

-- 2. how many products are of regular type?

select count(*) as regular_product_count
from product
where type = 'regular';

-- 3. how much spending has been done on marketing of product id 1?

select sum(marketing) as total_marketing
from fact
where productid = 1;

-- 4. what is the minimum sales of a product?

select min(sales) as min_sales
from fact;

-- 5. display the max cost of goods sold (cogs)

select max(cogs) as max_cogs
from fact;

-- 6. display the details of the product where product type is coffee

select *
from product
where product_type = 'coffee';

-- 7. display the details where total expenses are greater than 40

select *
from fact
where total_expenses > 40;

-- 8. what is the average sales in area code 719?

select avg(sales) as avg_sales
from fact
where area_code = 719;

-- 9. find out the total profit generated by colorado state
-- using joins

select sum(f.profit) as total_profit
from fact f
join location l
    on f.area_code = l.area_code
where l.state = 'colorado';

-- using subquery

select sum(profit) as total_profit
from fact
where area_code in (
    select area_code
    from location
    where state = 'colorado'
);

-- 10. display the average inventory for each product id

select productid, avg(inventory) as avg_inventory
from fact
group by productid
order by productid;

-- 11. display state in a sequential order in location table

select state
from location
order by state;

-- 12. display the average budget where budget margin > 100

select avg(budget_margin) as avg_budget
from fact
where budget_margin > 100;

-- 13. what is the total sales done on date 2010-01-01?

select sum(sales) as total_sales
from fact
where date = '2010-01-01';

-- 14. display the average total expense of each product id on an individual date

select date, productid, avg(total_expenses) as avg_expense
from fact
group by date, productid;

-- 15. display combined table details

select 
    f.date,
    f.productid,
    p.product_type,
    p.product,
    f.sales,
    f.profit,
    l.state,
    f.area_code
from fact f
join location l
    on f.area_code = l.area_code
join product p
    on f.productid = p.productid;

-- 16. display rank without gap (sales wise rank)

select 
    sales,
    dense_rank() over (order by sales desc) as sales_rank
from fact;

-- 17. find the state wise profit and sales

select 
    l.state,
    sum(f.profit) as total_profit,
    sum(f.sales) as total_sales
from fact f
join location l
    on f.area_code = l.area_code
group by l.state;

-- 18. find the state wise profit and sales along with product type

select 
    l.state,
    p.product_type,
    sum(f.profit) as total_profit,
    sum(f.sales) as total_sales
from fact f
join location l
    on f.area_code = l.area_code
join product p
    on f.productid = p.productid
group by l.state, p.product_type;

-- 19. if there is an increase in sales of 5%, calculate increased sales

select 
    sales,
    sales * 1.05 as increased_sales
from fact;

-- 20. find the maximum profit along with product id and product type

select 
    f.productid,
    p.product_type,
    f.profit
from fact f
join product p
    on f.productid = p.productid
where f.profit = (select max(profit) from fact);

-- 21. stored procedure to fetch result based on product type

create procedure sp_getproductbytype
    @producttype varchar(50)
as
begin
    select *
    from product
    where product_type = @producttype;
end;
go
exec sp_getproductbytype 'coffee';

-- 22. profit or loss based on total expenses

select 
    productid,
    total_expenses,
    case 
        when total_expenses < 60 then 'profit'
        else 'loss'
    end as status
from fact;

-- 23. total weekly sales using rollup

select 
    datepart(week, date) as week_no,
    date,
    productid,
    sum(sales) as total_weekly_sales
from fact
group by rollup (datepart(week, date), date, productid)
order by week_no;

-- 24. union and intersect on area_code

select area_code from fact
union
select area_code from location;

select area_code from fact
intersect
select area_code from location;

-- 25. user defined function to fetch product by preference

create function dbo.fn_getproducttype
(
    @producttype varchar(50)
)
returns table
as
return
(
    select *
    from product
    where product_type = @producttype
);
go
select * from dbo.fn_getproducttype('coffee');

-- 26. change product type coffee to tea and undo it

update product
set product_type = 'tea'
where productid = 1;

update product
set product_type = 'coffee'
where productid = 1;

-- 27. date, product id and sales where expenses between 100 and 200

select date, productid, sales
from fact
where total_expenses between 100 and 200;

-- 28. delete records for regular type

delete from product
where type = 'regular';

-- 29. ascii value of 5th character from product column

select 
    product,
    ascii(substring(product, 5, 1)) as ascii_value
from product;
